-- Migration: Ensure notes table exists with correct structure and RLS policies for the memory feature.
-- Executed at: 2026-01-25T20:49:12Z
-- Generated by AI Agent

create table if not exists notes (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table notes enable row level security;

create policy "Users can insert their own notes"
on notes for insert
with check (auth.uid() = user_id);

create policy "Users can view their own notes"
on notes for select
using (auth.uid() = user_id);
