-- Migration: Ensure messages table exists with correct structure and RLS policies for secure user access.
-- Executed at: 2026-01-24T21:06:33Z
-- Generated by AI Agent

create table if not exists messages (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null default auth.uid(),
  content text not null,
  is_user boolean not null default true,
  created_at timestamptz default now()
);

alter table messages enable row level security;

create policy "Users can select their own messages"
  on messages for select
  using (auth.uid() = user_id);

create policy "Users can insert their own messages"
  on messages for insert
  with check (auth.uid() = user_id);

