-- Migration: Create a new table 'messages' if it doesn't exist, or ensure it has the correct structure for the chat application. This is a safety check to ensure the database schema matches the code expectations.
-- Executed at: 2026-01-24T23:37:33Z
-- Generated by AI Agent

CREATE TABLE IF NOT EXISTS messages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  content TEXT NOT NULL,
  is_user BOOLEAN DEFAULT TRUE,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Create policy to allow users to see only their own messages
CREATE POLICY "Users can select their own messages" ON messages
  FOR SELECT USING (auth.uid() = user_id);

-- Create policy to allow users to insert their own messages
CREATE POLICY "Users can insert their own messages" ON messages
  FOR INSERT WITH CHECK (auth.uid() = user_id);

