-- Migration: Ensuring the notes table exists with correct structure and RLS policies for the new feature.
-- Executed at: 2026-01-25T20:40:20Z
-- Generated by AI Agent

create table if not exists notes (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  content text not null,
  created_at timestamptz default now()
);

alter table notes enable row level security;

-- Policy for users to view their own notes
create policy "Users can view their own notes" 
on notes for select 
using (auth.uid() = user_id);

-- Policy for users to insert their own notes
create policy "Users can insert their own notes" 
on notes for insert 
with check (auth.uid() = user_id);

-- Policy for service role (Edge Functions) to have full access
-- (Service role bypasses RLS by default, but good to be explicit if needed, 
-- though usually not required if using service_role key)

