import 'dart:async';

import 'package:supabase_flutter/supabase_flutter.dart';

/// Supabase configuration + helpers generated by Codex.
///
/// Always call [SupabaseConfig.ensureInitialized] before touching
/// [Supabase.instance] so credentials coming from the environment are
/// respected and the client is initialized exactly once per isolate.
class SupabaseConfig {
  const SupabaseConfig._();

  /// Default credentials generated when you linked the Supabase project.
  /// These lines are intentionally constant so Flutter web/desktop builds
  /// keep working even if no `--dart-define` values are passed.
  static const String supabaseUrl = 'https://nyfyxhpugahsdgowqhhl.supabase.co';
  static const String supabaseAnonKey =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55Znl4aHB1Z2Foc2Rnb3dxaGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzMTAzOTIsImV4cCI6MjA4NDg4NjM5Mn0.4mjsq--Bh_HczHek6b6UN2tCFk0wSdg5FEc1TMDat_w';

  /// Optional overrides via `--dart-define` or environment variables. If set,
  /// these take precedence over the defaults above.
  static const String _envSupabaseUrl = String.fromEnvironment(
    'SUPABASE_URL',
    defaultValue: '',
  );
  static const String _envSupabaseAnonKey = String.fromEnvironment(
    'SUPABASE_ANON_KEY',
    defaultValue: '',
  );

  static Future<void>? _initialization;

  /// Initializes `supabase_flutter` only once (per isolate) using the
  /// environment-provided URL + anon key.
  static Future<void> ensureInitialized() async {
    if (_isReady) {
      return;
    }

    _validateEnv();

    _initialization ??= Supabase.initialize(
      url: _effectiveSupabaseUrl,
      anonKey: _effectiveSupabaseAnonKey,
    );

    try {
      await _initialization;
    } catch (error) {
      _initialization = null;
      rethrow;
    }
  }

  static SupabaseClient get client {
    if (!_isReady) {
      throw StateError(
        'Supabase is not initialized. Call await SupabaseConfig.ensureInitialized() before using the client.',
      );
    }

    return Supabase.instance.client;
  }

  static bool get _isReady {
    try {
      Supabase.instance.client;
      return true;
    } catch (_) {
      return false;
    }
  }

  static void _validateEnv() {
    if (_effectiveSupabaseUrl.isEmpty || _effectiveSupabaseAnonKey.isEmpty) {
      throw StateError(
        'Missing Supabase credentials. Pass --dart-define SUPABASE_URL and SUPABASE_ANON_KEY when running the app.',
      );
    }
  }

  static String get _effectiveSupabaseUrl =>
      _envSupabaseUrl.isEmpty ? supabaseUrl : _envSupabaseUrl;

  static String get _effectiveSupabaseAnonKey =>
      _envSupabaseAnonKey.isEmpty ? supabaseAnonKey : _envSupabaseAnonKey;
}

/// Wrapper around Supabase Edge Functions.
///
/// Always use this helper so Supabase attaches the logged-in user's JWT
/// and satisfies "Verify JWT" on every Edge Function invocation.
class SupabaseEdgeFunctions {
  const SupabaseEdgeFunctions._();

  static Future<FunctionResponse> invoke(
    String functionName, {
    Object? body,
    Map<String, String>? headers,
  }) async {
    await SupabaseConfig.ensureInitialized();

    return SupabaseConfig.client.functions.invoke(
      functionName,
      body: body,
      headers: headers,
    );
  }
}
