// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: nyfyxhpugahsdgowqhhl

class SupabaseConfig {
  static const String supabaseUrl = 'https://nyfyxhpugahsdgowqhhl.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55Znl4aHB1Z2Foc2Rnb3dxaGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzMTAzOTIsImV4cCI6MjA4NDg4NjM5Mn0.4mjsq--Bh_HczHek6b6UN2tCFk0wSdg5FEc1TMDat_w';
}
